CI: sign and publish packages
osam-cologne/archlinux-proaudio pull request #16
Opened 2022-03-20 13:25 UTC by cbix

- [x] sign packages using [drone-gpgsign](https://plugins.drone.io/drone-plugins/drone-gpgsign/) plugin
- [x] `repo-add` all built packages
- [ ] sign db (?)
- [ ] push to arch.osamc.de using rsync

2022-03-20 13:51 UTC, SpotlightKid commented
Should we create an arch.osamc.de master key to sign member keys and the key used by the CI?

2022-03-20 13:55 UTC, cbix commented
> Should we create an arch.osamc.de master key to sign member keys and the key used by the CI?

@SpotlightKid yes! Good idea 👍 Haven't really wrapped my head around how in the end users will import this key easily in order to use the repo...

My approach at creating the repo db was actually to always create a fresh db and add all built packages when pushing to `master`, but that would mean we can't just manually tweak that db and add packages without using the CI. What do you think?

2022-03-20 16:03 UTC, SpotlightKid commented
> Haven't really wrapped my head around how in the end users will import this key easily in order to use the repo...

Like it is described here: https://wiki.archlinux.org/title/Pacman/Package_signing#Adding_unofficial_keys

We can copy the relevant parts into our top-level readme or put it into a GH wiki page.

Then list we list our repo [here](https://wiki.archlinux.org/title/Unofficial_user_repositories) and insert a link in the description to the above instructions.

2022-03-20 16:06 UTC, SpotlightKid commented
> [... ]always create a fresh db and add all built packages when pushing to `master`, [...]. What do you think?

Can't we cache the DB in the CI environment somewhere? If not, I would just download it with rsync from the repo server before doing the `repo-add`. If we sign the DB and check the sig after download that should make sure it stays consistent.

2022-03-20 16:07 UTC, cbix commented
> [...] I would just download it with rsync from the repo server before doing the `repo-add`.

just added that to the TODO 👍

2022-03-21 18:12 UTC, cbix commented
@SpotlightKid I hope my documentation matches your request :D

2022-03-21 19:05 UTC, SpotlightKid requested changes

2022-03-21 19:05 UTC, SpotlightKid commented on tools/README.md
> +Most of the tools in this directory are being used by the CI Build / Check / Publish pipeline, so here's a rough
suggestion: "[...] pipeline, which uses [Drone.io](https://www.drone.io/], [...]"

2022-03-22 08:45 UTC, cbix commented on tools/README.md
> +and stored as a Drone secret. The public key is exported using
b837dea09fc2d2c3a92d2bf62550fdb7f22b9227

2022-03-22 08:45 UTC, cbix commented on tools/README.md
> +The server is a simple web server and only requires all published files to sit in the same directory.
b837dea09fc2d2c3a92d2bf62550fdb7f22b9227

2022-03-22 08:45 UTC, cbix commented on tools/README.md
> +Most of the tools in this directory are being used by the CI Build / Check / Publish pipeline, so here's a rough
b837dea09fc2d2c3a92d2bf62550fdb7f22b9227

2022-03-22 08:49 UTC, cbix commented on tools/README.md
> +and stored as a Drone secret. The public key is exported using
(don't worry, I used `head -c 500 /dev/urandom | base64 -w0` to generate the dummy base64 "private key" 😜)

2022-03-22 09:37 UTC, merged

2022-03-22 13:53 UTC, cbix commented on tools/README.md
> +```
Oops :D Will open another small PR including this fix later today!