package rtcqs
osam-cologne/archlinux-proaudio pull request #62
Opened 2022-05-16 16:23 UTC by cbix

https://codeberg.org/rtcqs/rtcqs

I may create another package for the `python-pysimplegui` optdepend, however that's not really proaudio-related ;)

2022-05-16 16:30 UTC, SpotlightKid commented
> I may create another package for the `python-pysimplegui` optdepend

I assume you have seen https://aur.archlinux.org/packages/python-pysimplegui

2022-05-17 16:20 UTC, SpotlightKid requested changes
The package installs the file

    /usr/lib/python3.10/site-packages/rtcqs/rtcqs_qt_gui.py

But when I try to run it, I get:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.10/site-packages/rtcqs/rtcqs_qt_gui.py", line 3, in <module>
    import PySimpleGUIQt as sg
ModuleNotFoundError: No module named 'PySimpleGUIQt'
```

Maybe it's worth an upstream ticket.

When I run `rtcqs_gui` it shows the following warning on the "Audio Group" tab:

> User chris is currently not in the audio group. Add yourself to the audio group with 'sudo usermod -a -G audio chris' and log in again. See also https://wiki.linuxaudio.org/wiki/system_configuration#audio_group

The correct group name to check on Arch Linux would be `realtime`.

Maybe also worth an upstream ticket.

2022-05-17 16:20 UTC, SpotlightKid commented on packages/rtcqs/PKGBUILD
> +  install -Dm644 LICENSE -t "$pkgdir"/usr/share/licenses/${pkgname}
Tiny nitpick: `$pkgname`

2022-05-17 16:28 UTC, SpotlightKid reviewed
Does upstream plan a new release including the `.desktop` file soon? Otherwise it might be worth adding the file from the repo to the `source` array and installing it manually.

2022-05-17 16:29 UTC, cbix commented on packages/rtcqs/PKGBUILD
> +  install -Dm644 LICENSE -t "$pkgdir"/usr/share/licenses/${pkgname}
f5f1a65e3ddce451167c8f7d7ed70dd56a7f6b94

2022-05-17 16:37 UTC, cbix commented
The Qt GUI is considered beta and neither included as a console script under `/usr/bin` nor installed as executable. I'd say we should not expect users trying to run that. If you want I can just remove it during build.

2022-05-17 16:43 UTC, cbix commented
> The correct group name to check on Arch Linux would be `realtime`.

Interesting, do you have a reference for this? For some reason I have both groups on my system.

2022-05-17 17:31 UTC, SpotlightKid commented
* https://wiki.archlinux.org/title/Realtime_process_management
* https://archlinux.org/packages/community/any/realtime-privileges/

2022-05-17 22:37 UTC, SpotlightKid commented
> If you want I can just remove it during build.

I think it's ok to just leave it there. It's a 0.x release after all.

2022-05-20 13:21 UTC, SpotlightKid approved these changes
LGTM

2022-05-20 18:25 UTC, merged

2022-05-21 11:39 UTC, cbix commented
@SpotlightKid I opened this issue now https://codeberg.org/rtcqs/rtcqs/issues/4